version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: hono-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
